# Generated by Django 4.2.7 on 2023-11-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='number_specialization',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
