# Generated by Django 4.2.7 on 2023-11-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_specialization_number_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='number_specialization',
            field=models.CharField(max_length=255),
        ),
    ]
